# Generated by Django 4.2.7 on 2025-10-14 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CONTRACT", "Contract"),
                            ("POLICY", "Policy Document"),
                            ("COMPLIANCE", "Compliance Document"),
                            ("CERTIFICATE", "Certificate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("version", models.CharField(default="1.0", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_id", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("SERVICE", "Service Agreement"),
                            ("SUPPLY", "Supply Contract"),
                            ("EMPLOYMENT", "Employment Contract"),
                            ("NDA", "Non-Disclosure Agreement"),
                            ("PARTNERSHIP", "Partnership Agreement"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending Approval"),
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("client_name", models.CharField(max_length=200)),
                (
                    "contract_value",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
