# Generated by Django 4.2.7 on 2025-10-14 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "department_type",
                    models.CharField(
                        choices=[
                            ("ENGINEERING", "Engineering"),
                            ("CONSULTING", "Consulting"),
                            ("MANAGEMENT", "Management"),
                            ("OPERATIONS", "Operations"),
                            ("FINANCE", "Finance"),
                            ("HR", "Human Resources"),
                            ("IT", "Information Technology"),
                            ("SALES", "Sales & Marketing"),
                            ("QUALITY", "Quality Assurance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "budget_allocated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("employee_count", models.PositiveIntegerField(default=0)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr_management.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=20, unique=True)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full Time"),
                            ("PART_TIME", "Part Time"),
                            ("CONTRACT", "Contract"),
                            ("INTERN", "Intern"),
                            ("CONSULTANT", "Consultant"),
                        ],
                        default="FULL_TIME",
                        max_length=20,
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ON_LEAVE", "On Leave"),
                            ("TERMINATED", "Terminated"),
                            ("RETIRED", "Retired"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("hire_date", models.DateField()),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("personal_email", models.EmailField(blank=True, max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state_province", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="Sweden", max_length=100)),
                ("office_location", models.CharField(blank=True, max_length=100)),
                ("work_phone", models.CharField(blank=True, max_length=20)),
                (
                    "skills",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of skills"
                    ),
                ),
                ("certifications", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr_management.department",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_employees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="TimeOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_off_type",
                    models.CharField(
                        choices=[
                            ("VACATION", "Vacation"),
                            ("SICK", "Sick Leave"),
                            ("PERSONAL", "Personal Leave"),
                            ("MATERNITY", "Maternity Leave"),
                            ("PATERNITY", "Paternity Leave"),
                            ("BEREAVEMENT", "Bereavement Leave"),
                            ("TRAINING", "Training/Conference"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("days_requested", models.DecimalField(decimal_places=1, max_digits=5)),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("DENIED", "Denied"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_time_off",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_off_requests",
                        to="hr_management.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INTERN", "Intern"),
                            ("JUNIOR", "Junior"),
                            ("SENIOR", "Senior"),
                            ("LEAD", "Lead"),
                            ("MANAGER", "Manager"),
                            ("DIRECTOR", "Director"),
                            ("VP", "Vice President"),
                            ("EXECUTIVE", "Executive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("requirements", models.TextField(blank=True)),
                ("responsibilities", models.TextField()),
                ("min_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("max_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="hr_management.department",
                    ),
                ),
            ],
            options={
                "ordering": ["department", "level", "title"],
                "unique_together": {("title", "department", "level")},
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hr_management.position",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Performance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_period",
                    models.CharField(
                        choices=[
                            ("QUARTERLY", "Quarterly"),
                            ("SEMI_ANNUAL", "Semi-Annual"),
                            ("ANNUAL", "Annual"),
                            ("PROBATION", "Probation Review"),
                            ("PROJECT", "Project Review"),
                        ],
                        max_length=20,
                    ),
                ),
                ("review_start_date", models.DateField()),
                ("review_end_date", models.DateField()),
                (
                    "technical_skills",
                    models.IntegerField(
                        choices=[
                            (1, "Needs Improvement"),
                            (2, "Meets Expectations"),
                            (3, "Exceeds Expectations"),
                            (4, "Outstanding"),
                            (5, "Exceptional"),
                        ]
                    ),
                ),
                (
                    "communication",
                    models.IntegerField(
                        choices=[
                            (1, "Needs Improvement"),
                            (2, "Meets Expectations"),
                            (3, "Exceeds Expectations"),
                            (4, "Outstanding"),
                            (5, "Exceptional"),
                        ]
                    ),
                ),
                (
                    "teamwork",
                    models.IntegerField(
                        choices=[
                            (1, "Needs Improvement"),
                            (2, "Meets Expectations"),
                            (3, "Exceeds Expectations"),
                            (4, "Outstanding"),
                            (5, "Exceptional"),
                        ]
                    ),
                ),
                (
                    "leadership",
                    models.IntegerField(
                        choices=[
                            (1, "Needs Improvement"),
                            (2, "Meets Expectations"),
                            (3, "Exceeds Expectations"),
                            (4, "Outstanding"),
                            (5, "Exceptional"),
                        ]
                    ),
                ),
                (
                    "initiative",
                    models.IntegerField(
                        choices=[
                            (1, "Needs Improvement"),
                            (2, "Meets Expectations"),
                            (3, "Exceeds Expectations"),
                            (4, "Outstanding"),
                            (5, "Exceptional"),
                        ]
                    ),
                ),
                ("overall_rating", models.DecimalField(decimal_places=2, max_digits=3)),
                ("strengths", models.TextField()),
                ("areas_for_improvement", models.TextField()),
                ("goals_next_period", models.TextField()),
                ("employee_comments", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reviews",
                        to="hr_management.employee",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conducted_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-review_end_date"],
                "unique_together": {("employee", "review_period", "review_end_date")},
            },
        ),
    ]
