# Generated by Django 4.2.7 on 2025-10-14 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lead_id", models.CharField(max_length=20, unique=True)),
                ("company_name", models.CharField(max_length=200)),
                ("contact_person", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "lead_source",
                    models.CharField(
                        choices=[
                            ("WEBSITE", "Website"),
                            ("REFERRAL", "Referral"),
                            ("COLD_CALL", "Cold Call"),
                            ("EMAIL_CAMPAIGN", "Email Campaign"),
                            ("TRADE_SHOW", "Trade Show"),
                            ("SOCIAL_MEDIA", "Social Media"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("CONTACTED", "Contacted"),
                            ("QUALIFIED", "Qualified"),
                            ("PROPOSAL", "Proposal Sent"),
                            ("NEGOTIATION", "Negotiation"),
                            ("WON", "Won"),
                            ("LOST", "Lost"),
                        ],
                        default="NEW",
                        max_length=15,
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "probability",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opportunity_id", models.CharField(max_length=20, unique=True)),
                ("opportunity_name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("PROSPECTING", "Prospecting"),
                            ("QUALIFICATION", "Qualification"),
                            ("NEEDS_ANALYSIS", "Needs Analysis"),
                            ("PROPOSAL", "Proposal/Quote"),
                            ("NEGOTIATION", "Negotiation"),
                            ("CLOSED_WON", "Closed Won"),
                            ("CLOSED_LOST", "Closed Lost"),
                        ],
                        default="PROSPECTING",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("probability", models.DecimalField(decimal_places=2, max_digits=5)),
                ("expected_close_date", models.DateField()),
                ("actual_close_date", models.DateField(blank=True, null=True)),
                ("competitor_info", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sales.lead"
                    ),
                ),
                (
                    "sales_rep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=20, unique=True)),
                ("company_name", models.CharField(max_length=200)),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("SMB", "Small/Medium Business"),
                            ("ENTERPRISE", "Enterprise"),
                            ("GOVERNMENT", "Government"),
                            ("NGO", "Non-Profit Organization"),
                        ],
                        max_length=15,
                    ),
                ),
                ("primary_contact", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("billing_address", models.TextField()),
                ("shipping_address", models.TextField(blank=True)),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("payment_terms", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campaign_name", models.CharField(max_length=200)),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email Campaign"),
                            ("SOCIAL_MEDIA", "Social Media"),
                            ("TRADE_SHOW", "Trade Show"),
                            ("WEBINAR", "Webinar"),
                            ("CONTENT", "Content Marketing"),
                            ("PPC", "Pay-Per-Click"),
                        ],
                        max_length=15,
                    ),
                ),
                ("description", models.TextField()),
                ("budget", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "spent_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Planning"),
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNING",
                        max_length=15,
                    ),
                ),
                ("target_audience", models.TextField()),
                ("campaign_metrics", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
