# Railway Deployment Configuration
# Optimized for production deployment using soft coding techniques

[build]
  builder = "nixpacks"

[deploy]
  healthcheckPath = "/health/"
  healthcheckTimeout = 300
  restartPolicyType = "always"

[variables]
  # Django Configuration
  DJANGO_SETTINGS_MODULE = "config.settings.railway_production"
  PYTHONPATH = "/app"
  
  # Railway-specific optimizations
  RAILWAY_DEPLOYMENT = "true"
  DEPLOYMENT_TARGET = "railway"
  
  # Cache and Database
  CACHE_TTL = "600"
  DB_POOL_SIZE = "20"
  
  # Security
  SECURE_SSL_REDIRECT = "false"
  SESSION_COOKIE_SECURE = "false"
  CSRF_COOKIE_SECURE = "false"

[environments.production]
  # Production environment variables
  DEBUG = "false"
  ALLOWED_HOSTS = "rejlers-backend-production.up.railway.app,.railway.app"
  
[environments.staging]
  # Staging environment (if needed)
  DEBUG = "true"
  ALLOWED_HOSTS = "rejlers-backend-staging.up.railway.app,.railway.app"