# Generated by Django 4.2.7 on 2025-10-14 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SafetyIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incident_id", models.CharField(max_length=50, unique=True)),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("INJURY", "Personal Injury"),
                            ("PROPERTY", "Property Damage"),
                            ("ENVIRONMENTAL", "Environmental"),
                            ("NEAR_MISS", "Near Miss"),
                            ("EQUIPMENT", "Equipment Failure"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=200)),
                ("incident_date", models.DateTimeField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnvironmentalMonitoring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monitoring_type",
                    models.CharField(
                        choices=[
                            ("AIR_QUALITY", "Air Quality"),
                            ("WATER_QUALITY", "Water Quality"),
                            ("NOISE_LEVEL", "Noise Level"),
                            ("WASTE_TRACKING", "Waste Tracking"),
                            ("ENERGY_CONSUMPTION", "Energy Consumption"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                (
                    "measured_value",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                ("unit_of_measure", models.CharField(max_length=50)),
                (
                    "threshold_limit",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("is_within_limits", models.BooleanField(default=True)),
                ("measurement_date", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComplianceChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "compliance_type",
                    models.CharField(
                        choices=[
                            ("SAFETY", "Safety Compliance"),
                            ("ENVIRONMENTAL", "Environmental Compliance"),
                            ("REGULATORY", "Regulatory Compliance"),
                            ("INTERNAL", "Internal Policy"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("checklist_items", models.JSONField(default=list)),
                ("is_mandatory", models.BooleanField(default=True)),
                ("frequency_days", models.IntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComplianceAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessed_location", models.CharField(max_length=200)),
                ("assessment_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("NON_COMPLIANT", "Non-Compliant"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "compliance_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("assessment_date", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hse_compliance.compliancechecklist",
                    ),
                ),
            ],
        ),
    ]
