# Generated by Django 4.2.7 on 2025-10-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hse_compliance', '0001_initial'),
    ]

    operations = [
    ]
