# Generated by Django 4.2.7 on 2025-10-17 05:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hse_compliance", "0002_auto_20251016_1130"),
    ]

    operations = []
