# Generated by Django 4.2.7 on 2025-10-14 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system_id", models.CharField(max_length=50, unique=True)),
                ("system_name", models.CharField(max_length=200)),
                (
                    "system_type",
                    models.CharField(
                        choices=[
                            ("SCADA", "SCADA System"),
                            ("DCS", "Distributed Control System"),
                            ("PLC", "Programmable Logic Controller"),
                            ("HMI", "Human Machine Interface"),
                            ("HISTORIAN", "Process Historian"),
                        ],
                        max_length=15,
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL", "Operational"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("OFFLINE", "Offline"),
                            ("FAULT", "Fault Condition"),
                        ],
                        default="OPERATIONAL",
                        max_length=15,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("port", models.IntegerField(blank=True, null=True)),
                ("configuration", models.JSONField(default=dict)),
                ("installed_date", models.DateField()),
                ("last_maintenance", models.DateField(blank=True, null=True)),
                ("next_maintenance", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(max_length=200)),
                (
                    "tag_type",
                    models.CharField(
                        choices=[
                            ("ANALOG_INPUT", "Analog Input"),
                            ("ANALOG_OUTPUT", "Analog Output"),
                            ("DIGITAL_INPUT", "Digital Input"),
                            ("DIGITAL_OUTPUT", "Digital Output"),
                            ("CALCULATED", "Calculated Value"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("FLOAT", "Float"),
                            ("INTEGER", "Integer"),
                            ("BOOLEAN", "Boolean"),
                            ("STRING", "String"),
                        ],
                        max_length=10,
                    ),
                ),
                ("unit_of_measure", models.CharField(blank=True, max_length=20)),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "alarm_high",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "alarm_low",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("scan_rate", models.IntegerField(default=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "control_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rto_apc.controlsystem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("PREVENTIVE", "Preventive Maintenance"),
                            ("CORRECTIVE", "Corrective Maintenance"),
                            ("PREDICTIVE", "Predictive Maintenance"),
                            ("EMERGENCY", "Emergency Maintenance"),
                        ],
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("scheduled_date", models.DateTimeField()),
                ("estimated_duration", models.DurationField()),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="SCHEDULED",
                        max_length=15,
                    ),
                ),
                ("work_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "control_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rto_apc.controlsystem",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_maintenance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("value", models.DecimalField(decimal_places=6, max_digits=15)),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("GOOD", "Good"),
                            ("BAD", "Bad"),
                            ("UNCERTAIN", "Uncertain"),
                        ],
                        default="GOOD",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rto_apc.processtag",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tag", "timestamp"],
                        name="rto_apc_pro_tag_id_62ab66_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="rto_apc_pro_timesta_72b322_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Alarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alarm_type",
                    models.CharField(
                        choices=[
                            ("HIGH", "High Alarm"),
                            ("LOW", "Low Alarm"),
                            ("DEVIATION", "Deviation Alarm"),
                            ("COMMUNICATION", "Communication Alarm"),
                            ("SYSTEM", "System Alarm"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.CharField(max_length=200)),
                ("alarm_value", models.DecimalField(decimal_places=6, max_digits=15)),
                ("setpoint", models.DecimalField(decimal_places=6, max_digits=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("CLEARED", "Cleared"),
                            ("SUPPRESSED", "Suppressed"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rto_apc.processtag",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "priority"],
                        name="rto_apc_ala_status_462807_idx",
                    ),
                    models.Index(
                        fields=["occurred_at"], name="rto_apc_ala_occurre_1fbde0_idx"
                    ),
                ],
            },
        ),
    ]
