# Generated by Django 4.2.7 on 2025-10-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(
                default="Rejlers", max_length=200, verbose_name="company name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(
                default="AI Team Lead", max_length=150, verbose_name="job title"
            ),
        ),
    ]
